checks:
  php:
    code_rating: true
    duplication: true

    python:
      code_rating: true
      duplicate_code: true

    ruby:
      code_rating: true
      duplicate_code: true

build:
  tests:
    override:
      -
        command: 'phpunit -c phpunit.xml --coverage-clover=./build/logs/clover.xml'
        coverage:
          file: './build/logs/clover.xml'
          format: 'php-clover'
