language: php
php:
  - nightly
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration=tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls
